### ISSUE TITLE
3D templates for BRATS

### ISSUE THREAD

**Issue by liamheng** [ntustison/ANTsAndArboles#1]
Hi, Nick.

Thank you for this awesome example. It works excellently.
And I want to apply this example on 3D data. Is your 3D templates of BRATS available somewhere?
Though I can build them with antsMultivariateTemplateConstruction.sh, it is still time-comsuming. So if your template is available, that will be amazing.

Thanks a lot.

Heng

**Comment by ntustison** [comment]
The MMRR template is the one used for this [paper](https://www.ncbi.nlm.nih.gov/pubmed/25433513).

https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436

**Comment by liamheng** [comment]
Thank you, Nick.

But I'm confused that you used templates of Flair, T1 and T2 in your framework. However, there is only MMRR template of T1. How about the Flair and T2?

Heng

**Comment by ntustison** [comment]
https://drive.google.com/drive/folders/0B4SvObeEfaRyaU9oT19ueUNyX1k?usp=sharing
